---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# ignore:
# vendor'd code (that has vendor in its path)
# protoc generated golang (*.pb.go)
exclude: vendor|\.pb\.go

repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.20.0
    hooks:
      - id: yamllint
        args:
          - --format=parsable
          - --strict

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.0.10
    hooks:
      - id: yamlfmt
        args:
          - --mapping=2
          - --sequence=4
          - --offset=2
          - --width=1200    # match .yamllint.yaml; we don't care about line-length.

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: pretty-format-json
        args:
          - --autofix
      - id: trailing-whitespace

  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.16
    hooks:
      - id: forbid-binary
      # See checks in shellcheck wiki: https://github.com/koalaman/shellcheck/wiki/
      - id: shellcheck
      - id: shfmt
        # do not use these args (yet):
        # -s, simplify code
        # -mn, minify to reduce its size
        args:
          - -w      # autofix in place
          - -d      # show diff
          - -i=2    # indent 2 spaces

  # Example usage of dotnet-format: pre-commit run dotnet-format --all-files
  - repo: local
    hooks:
      - id: dotnet-format
        name: dotnet-format
        entry: script/check-dotnet-format.sh
        language: script
        types:
          - file
          - text
        pass_filenames: false
        files: ^.*/.*.cs$
        args:
          - ./samples/
          - --folder

